version: "3.9"

services:
  openrlhf-dev:
    image: bjaramillo/custom-kaggle-cpu-dev
    platform: "linux/amd64"
    volumes:
      - .:/kaggle/input/openrlhf-fork-codebase
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface